#include "stdafx.h"
#include "GameMaster.h"


GameMaster::GameMaster(const int height, const int width)
{
	size[0] = height;
	size[1] = width;
}

void GameMaster::Instructions() {
	std::string instructions;
	instructions = "Welcome to the Mastermind!\n\n";
	instructions += "To play the MasterMind, you will have to find the color randomly generated by the failsafe AI.\n";
	instructions += "Five colors between yellow(Y), blue(B), purple(P), orange(O), green(G) will form the key that you need to find.\n";
	instructions += "Each turn you will give four colors that you think might form the key and\nthe AI will reveal the number of matching colors that are in the key ";
	instructions += "as well as how many colors are correctly placed.\n";
	instructions += "It won't tell which one though, so think well\nso you can be the Mastermind!";
	std::cout << instructions << std::endl;
}

void GameMaster::CreateGrid(const int& height, const int& width) {
	grid = new std::string **[height];
	for (int i = 0; i < height; i++) {
		grid[i] = new std::string *[width + 2];
		for (int j = 0; j < width; j++) {
			grid[i][j] = new std::string("   ");
		}
	}
}

void GameMaster::Play() {
	CreateGrid(size[0], size[1]);
	Instructions();
}

GameMaster::~GameMaster() {
	for (int i = 0; i < size[0]; i++) {
		delete[] grid[i];
	}
	delete[] grid;
}
